// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.0
// source: qrl-rewards/types/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidatorEpochIncome struct {
	state                              protoimpl.MessageState `protogen:"open.v1"`
	AttestationSourceReward            uint64                 `protobuf:"varint,2,opt,name=attestation_source_reward,json=attestationSourceReward,proto3" json:"attestation_source_reward,omitempty"`
	AttestationSourcePenalty           uint64                 `protobuf:"varint,3,opt,name=attestation_source_penalty,json=attestationSourcePenalty,proto3" json:"attestation_source_penalty,omitempty"`
	AttestationTargetReward            uint64                 `protobuf:"varint,4,opt,name=attestation_target_reward,json=attestationTargetReward,proto3" json:"attestation_target_reward,omitempty"`
	AttestationTargetPenalty           uint64                 `protobuf:"varint,5,opt,name=attestation_target_penalty,json=attestationTargetPenalty,proto3" json:"attestation_target_penalty,omitempty"`
	AttestationHeadReward              uint64                 `protobuf:"varint,6,opt,name=attestation_head_reward,json=attestationHeadReward,proto3" json:"attestation_head_reward,omitempty"`
	FinalityDelayPenalty               uint64                 `protobuf:"varint,7,opt,name=finality_delay_penalty,json=finalityDelayPenalty,proto3" json:"finality_delay_penalty,omitempty"`
	ProposerSlashingInclusionReward    uint64                 `protobuf:"varint,8,opt,name=proposer_slashing_inclusion_reward,json=proposerSlashingInclusionReward,proto3" json:"proposer_slashing_inclusion_reward,omitempty"`
	ProposerAttestationInclusionReward uint64                 `protobuf:"varint,9,opt,name=proposer_attestation_inclusion_reward,json=proposerAttestationInclusionReward,proto3" json:"proposer_attestation_inclusion_reward,omitempty"`
	ProposerSyncInclusionReward        uint64                 `protobuf:"varint,10,opt,name=proposer_sync_inclusion_reward,json=proposerSyncInclusionReward,proto3" json:"proposer_sync_inclusion_reward,omitempty"`
	SyncCommitteeReward                uint64                 `protobuf:"varint,11,opt,name=sync_committee_reward,json=syncCommitteeReward,proto3" json:"sync_committee_reward,omitempty"`
	SyncCommitteePenalty               uint64                 `protobuf:"varint,12,opt,name=sync_committee_penalty,json=syncCommitteePenalty,proto3" json:"sync_committee_penalty,omitempty"`
	SlashingReward                     uint64                 `protobuf:"varint,13,opt,name=slashing_reward,json=slashingReward,proto3" json:"slashing_reward,omitempty"`
	SlashingPenalty                    uint64                 `protobuf:"varint,14,opt,name=slashing_penalty,json=slashingPenalty,proto3" json:"slashing_penalty,omitempty"`
	TxFeeRewardPlanck                  []byte                 `protobuf:"bytes,15,opt,name=tx_fee_reward_planck,json=txFeeRewardPlanck,proto3" json:"tx_fee_reward_planck,omitempty"`
	ProposalsMissed                    uint64                 `protobuf:"varint,16,opt,name=proposals_missed,json=proposalsMissed,proto3" json:"proposals_missed,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *ValidatorEpochIncome) Reset() {
	*x = ValidatorEpochIncome{}
	mi := &file_qrl_rewards_types_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorEpochIncome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorEpochIncome) ProtoMessage() {}

func (x *ValidatorEpochIncome) ProtoReflect() protoreflect.Message {
	mi := &file_qrl_rewards_types_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorEpochIncome.ProtoReflect.Descriptor instead.
func (*ValidatorEpochIncome) Descriptor() ([]byte, []int) {
	return file_qrl_rewards_types_types_proto_rawDescGZIP(), []int{0}
}

func (x *ValidatorEpochIncome) GetAttestationSourceReward() uint64 {
	if x != nil {
		return x.AttestationSourceReward
	}
	return 0
}

func (x *ValidatorEpochIncome) GetAttestationSourcePenalty() uint64 {
	if x != nil {
		return x.AttestationSourcePenalty
	}
	return 0
}

func (x *ValidatorEpochIncome) GetAttestationTargetReward() uint64 {
	if x != nil {
		return x.AttestationTargetReward
	}
	return 0
}

func (x *ValidatorEpochIncome) GetAttestationTargetPenalty() uint64 {
	if x != nil {
		return x.AttestationTargetPenalty
	}
	return 0
}

func (x *ValidatorEpochIncome) GetAttestationHeadReward() uint64 {
	if x != nil {
		return x.AttestationHeadReward
	}
	return 0
}

func (x *ValidatorEpochIncome) GetFinalityDelayPenalty() uint64 {
	if x != nil {
		return x.FinalityDelayPenalty
	}
	return 0
}

func (x *ValidatorEpochIncome) GetProposerSlashingInclusionReward() uint64 {
	if x != nil {
		return x.ProposerSlashingInclusionReward
	}
	return 0
}

func (x *ValidatorEpochIncome) GetProposerAttestationInclusionReward() uint64 {
	if x != nil {
		return x.ProposerAttestationInclusionReward
	}
	return 0
}

func (x *ValidatorEpochIncome) GetProposerSyncInclusionReward() uint64 {
	if x != nil {
		return x.ProposerSyncInclusionReward
	}
	return 0
}

func (x *ValidatorEpochIncome) GetSyncCommitteeReward() uint64 {
	if x != nil {
		return x.SyncCommitteeReward
	}
	return 0
}

func (x *ValidatorEpochIncome) GetSyncCommitteePenalty() uint64 {
	if x != nil {
		return x.SyncCommitteePenalty
	}
	return 0
}

func (x *ValidatorEpochIncome) GetSlashingReward() uint64 {
	if x != nil {
		return x.SlashingReward
	}
	return 0
}

func (x *ValidatorEpochIncome) GetSlashingPenalty() uint64 {
	if x != nil {
		return x.SlashingPenalty
	}
	return 0
}

func (x *ValidatorEpochIncome) GetTxFeeRewardPlanck() []byte {
	if x != nil {
		return x.TxFeeRewardPlanck
	}
	return nil
}

func (x *ValidatorEpochIncome) GetProposalsMissed() uint64 {
	if x != nil {
		return x.ProposalsMissed
	}
	return 0
}

var File_qrl_rewards_types_types_proto protoreflect.FileDescriptor

const file_qrl_rewards_types_types_proto_rawDesc = "" +
	"\n" +
	"\x1dqrl-rewards/types/types.proto\x12\x05types\"\xf7\x06\n" +
	"\x14ValidatorEpochIncome\x12:\n" +
	"\x19attestation_source_reward\x18\x02 \x01(\x04R\x17attestationSourceReward\x12<\n" +
	"\x1aattestation_source_penalty\x18\x03 \x01(\x04R\x18attestationSourcePenalty\x12:\n" +
	"\x19attestation_target_reward\x18\x04 \x01(\x04R\x17attestationTargetReward\x12<\n" +
	"\x1aattestation_target_penalty\x18\x05 \x01(\x04R\x18attestationTargetPenalty\x126\n" +
	"\x17attestation_head_reward\x18\x06 \x01(\x04R\x15attestationHeadReward\x124\n" +
	"\x16finality_delay_penalty\x18\a \x01(\x04R\x14finalityDelayPenalty\x12K\n" +
	"\"proposer_slashing_inclusion_reward\x18\b \x01(\x04R\x1fproposerSlashingInclusionReward\x12Q\n" +
	"%proposer_attestation_inclusion_reward\x18\t \x01(\x04R\"proposerAttestationInclusionReward\x12C\n" +
	"\x1eproposer_sync_inclusion_reward\x18\n" +
	" \x01(\x04R\x1bproposerSyncInclusionReward\x122\n" +
	"\x15sync_committee_reward\x18\v \x01(\x04R\x13syncCommitteeReward\x124\n" +
	"\x16sync_committee_penalty\x18\f \x01(\x04R\x14syncCommitteePenalty\x12'\n" +
	"\x0fslashing_reward\x18\r \x01(\x04R\x0eslashingReward\x12)\n" +
	"\x10slashing_penalty\x18\x0e \x01(\x04R\x0fslashingPenalty\x12/\n" +
	"\x14tx_fee_reward_planck\x18\x0f \x01(\fR\x11txFeeRewardPlanck\x12)\n" +
	"\x10proposals_missed\x18\x10 \x01(\x04R\x0fproposalsMissedB\tZ\a./typesb\x06proto3"

var (
	file_qrl_rewards_types_types_proto_rawDescOnce sync.Once
	file_qrl_rewards_types_types_proto_rawDescData []byte
)

func file_qrl_rewards_types_types_proto_rawDescGZIP() []byte {
	file_qrl_rewards_types_types_proto_rawDescOnce.Do(func() {
		file_qrl_rewards_types_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qrl_rewards_types_types_proto_rawDesc), len(file_qrl_rewards_types_types_proto_rawDesc)))
	})
	return file_qrl_rewards_types_types_proto_rawDescData
}

var file_qrl_rewards_types_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_qrl_rewards_types_types_proto_goTypes = []any{
	(*ValidatorEpochIncome)(nil), // 0: types.ValidatorEpochIncome
}
var file_qrl_rewards_types_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_qrl_rewards_types_types_proto_init() }
func file_qrl_rewards_types_types_proto_init() {
	if File_qrl_rewards_types_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qrl_rewards_types_types_proto_rawDesc), len(file_qrl_rewards_types_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qrl_rewards_types_types_proto_goTypes,
		DependencyIndexes: file_qrl_rewards_types_types_proto_depIdxs,
		MessageInfos:      file_qrl_rewards_types_types_proto_msgTypes,
	}.Build()
	File_qrl_rewards_types_types_proto = out.File
	file_qrl_rewards_types_types_proto_goTypes = nil
	file_qrl_rewards_types_types_proto_depIdxs = nil
}
