// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.0
// source: types/execution.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecutionBlock is stored in the blocks table under <chainID>:<reversePaddedNumber>
type ExecutionBlock struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Hash          []byte                  `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentHash    []byte                  `protobuf:"bytes,2,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Coinbase      []byte                  `protobuf:"bytes,4,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	Root          []byte                  `protobuf:"bytes,5,opt,name=root,proto3" json:"root,omitempty"`
	TxHash        []byte                  `protobuf:"bytes,6,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	ReceiptHash   []byte                  `protobuf:"bytes,7,opt,name=receipt_hash,json=receiptHash,proto3" json:"receipt_hash,omitempty"`
	Number        uint64                  `protobuf:"varint,9,opt,name=number,proto3" json:"number,omitempty"`
	GasLimit      uint64                  `protobuf:"varint,10,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed       uint64                  `protobuf:"varint,11,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Time          *timestamppb.Timestamp  `protobuf:"bytes,12,opt,name=time,proto3" json:"time,omitempty"`
	Extra         []byte                  `protobuf:"bytes,13,opt,name=extra,proto3" json:"extra,omitempty"`
	Random        []byte                  `protobuf:"bytes,14,opt,name=random,proto3" json:"random,omitempty"`
	Bloom         []byte                  `protobuf:"bytes,17,opt,name=bloom,proto3" json:"bloom,omitempty"`
	BaseFee       []byte                  `protobuf:"bytes,18,opt,name=base_fee,json=baseFee,proto3" json:"base_fee,omitempty"`
	Transactions  []*ExecutionTransaction `protobuf:"bytes,21,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Withdrawals   []*ExecutionWithdrawal  `protobuf:"bytes,22,rep,name=withdrawals,proto3" json:"withdrawals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionBlock) Reset() {
	*x = ExecutionBlock{}
	mi := &file_types_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionBlock) ProtoMessage() {}

func (x *ExecutionBlock) ProtoReflect() protoreflect.Message {
	mi := &file_types_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionBlock.ProtoReflect.Descriptor instead.
func (*ExecutionBlock) Descriptor() ([]byte, []int) {
	return file_types_execution_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionBlock) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ExecutionBlock) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *ExecutionBlock) GetCoinbase() []byte {
	if x != nil {
		return x.Coinbase
	}
	return nil
}

func (x *ExecutionBlock) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *ExecutionBlock) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *ExecutionBlock) GetReceiptHash() []byte {
	if x != nil {
		return x.ReceiptHash
	}
	return nil
}

func (x *ExecutionBlock) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *ExecutionBlock) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *ExecutionBlock) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *ExecutionBlock) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ExecutionBlock) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *ExecutionBlock) GetRandom() []byte {
	if x != nil {
		return x.Random
	}
	return nil
}

func (x *ExecutionBlock) GetBloom() []byte {
	if x != nil {
		return x.Bloom
	}
	return nil
}

func (x *ExecutionBlock) GetBaseFee() []byte {
	if x != nil {
		return x.BaseFee
	}
	return nil
}

func (x *ExecutionBlock) GetTransactions() []*ExecutionTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ExecutionBlock) GetWithdrawals() []*ExecutionWithdrawal {
	if x != nil {
		return x.Withdrawals
	}
	return nil
}

type ExecutionWithdrawal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Index          uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ValidatorIndex uint64                 `protobuf:"varint,2,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty"`
	Address        []byte                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Amount         []byte                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutionWithdrawal) Reset() {
	*x = ExecutionWithdrawal{}
	mi := &file_types_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionWithdrawal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionWithdrawal) ProtoMessage() {}

func (x *ExecutionWithdrawal) ProtoReflect() protoreflect.Message {
	mi := &file_types_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionWithdrawal.ProtoReflect.Descriptor instead.
func (*ExecutionWithdrawal) Descriptor() ([]byte, []int) {
	return file_types_execution_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionWithdrawal) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ExecutionWithdrawal) GetValidatorIndex() uint64 {
	if x != nil {
		return x.ValidatorIndex
	}
	return 0
}

func (x *ExecutionWithdrawal) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ExecutionWithdrawal) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

type ExecutionTransaction struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Type                 uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Nonce                uint64                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	MaxPriorityFeePerGas []byte                 `protobuf:"bytes,4,opt,name=max_priority_fee_per_gas,json=maxPriorityFeePerGas,proto3" json:"max_priority_fee_per_gas,omitempty"`
	MaxFeePerGas         []byte                 `protobuf:"bytes,5,opt,name=max_fee_per_gas,json=maxFeePerGas,proto3" json:"max_fee_per_gas,omitempty"`
	Gas                  uint64                 `protobuf:"varint,6,opt,name=gas,proto3" json:"gas,omitempty"`
	Value                []byte                 `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	Data                 []byte                 `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	To                   []byte                 `protobuf:"bytes,12,opt,name=to,proto3" json:"to,omitempty"`
	From                 []byte                 `protobuf:"bytes,13,opt,name=from,proto3" json:"from,omitempty"`
	ChainId              []byte                 `protobuf:"bytes,14,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	AccessList           []*AccessList          `protobuf:"bytes,15,rep,name=access_list,json=accessList,proto3" json:"access_list,omitempty"`
	Hash                 []byte                 `protobuf:"bytes,16,opt,name=hash,proto3" json:"hash,omitempty"`
	// Receipt fields
	ContractAddress    []byte          `protobuf:"bytes,17,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	CommulativeGasUsed uint64          `protobuf:"varint,18,opt,name=commulative_gas_used,json=commulativeGasUsed,proto3" json:"commulative_gas_used,omitempty"`
	GasUsed            uint64          `protobuf:"varint,19,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	LogsBloom          []byte          `protobuf:"bytes,20,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	Status             uint64          `protobuf:"varint,21,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMsg           string          `protobuf:"bytes,22,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Logs               []*ExecutionLog `protobuf:"bytes,23,rep,name=logs,proto3" json:"logs,omitempty"`
	// Internal transactions
	Itx           []*ExecutionInternalTransaction `protobuf:"bytes,24,rep,name=itx,proto3" json:"itx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionTransaction) Reset() {
	*x = ExecutionTransaction{}
	mi := &file_types_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionTransaction) ProtoMessage() {}

func (x *ExecutionTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_types_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionTransaction.ProtoReflect.Descriptor instead.
func (*ExecutionTransaction) Descriptor() ([]byte, []int) {
	return file_types_execution_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionTransaction) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ExecutionTransaction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *ExecutionTransaction) GetMaxPriorityFeePerGas() []byte {
	if x != nil {
		return x.MaxPriorityFeePerGas
	}
	return nil
}

func (x *ExecutionTransaction) GetMaxFeePerGas() []byte {
	if x != nil {
		return x.MaxFeePerGas
	}
	return nil
}

func (x *ExecutionTransaction) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *ExecutionTransaction) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ExecutionTransaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecutionTransaction) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ExecutionTransaction) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ExecutionTransaction) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *ExecutionTransaction) GetAccessList() []*AccessList {
	if x != nil {
		return x.AccessList
	}
	return nil
}

func (x *ExecutionTransaction) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ExecutionTransaction) GetContractAddress() []byte {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

func (x *ExecutionTransaction) GetCommulativeGasUsed() uint64 {
	if x != nil {
		return x.CommulativeGasUsed
	}
	return 0
}

func (x *ExecutionTransaction) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *ExecutionTransaction) GetLogsBloom() []byte {
	if x != nil {
		return x.LogsBloom
	}
	return nil
}

func (x *ExecutionTransaction) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ExecutionTransaction) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ExecutionTransaction) GetLogs() []*ExecutionLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ExecutionTransaction) GetItx() []*ExecutionInternalTransaction {
	if x != nil {
		return x.Itx
	}
	return nil
}

type IsContractUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsContract    bool                   `protobuf:"varint,1,opt,name=is_contract,json=isContract,proto3" json:"is_contract,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsContractUpdate) Reset() {
	*x = IsContractUpdate{}
	mi := &file_types_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsContractUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsContractUpdate) ProtoMessage() {}

func (x *IsContractUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_types_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsContractUpdate.ProtoReflect.Descriptor instead.
func (*IsContractUpdate) Descriptor() ([]byte, []int) {
	return file_types_execution_proto_rawDescGZIP(), []int{3}
}

func (x *IsContractUpdate) GetIsContract() bool {
	if x != nil {
		return x.IsContract
	}
	return false
}

func (x *IsContractUpdate) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AccessList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	StorageKeys   [][]byte               `protobuf:"bytes,2,rep,name=storage_keys,json=storageKeys,proto3" json:"storage_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessList) Reset() {
	*x = AccessList{}
	mi := &file_types_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessList) ProtoMessage() {}

func (x *AccessList) ProtoReflect() protoreflect.Message {
	mi := &file_types_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessList.ProtoReflect.Descriptor instead.
func (*AccessList) Descriptor() ([]byte, []int) {
	return file_types_execution_proto_rawDescGZIP(), []int{4}
}

func (x *AccessList) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *AccessList) GetStorageKeys() [][]byte {
	if x != nil {
		return x.StorageKeys
	}
	return nil
}

type ExecutionLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Removed       bool                   `protobuf:"varint,3,opt,name=removed,proto3" json:"removed,omitempty"`
	Topics        [][]byte               `protobuf:"bytes,4,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionLog) Reset() {
	*x = ExecutionLog{}
	mi := &file_types_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionLog) ProtoMessage() {}

func (x *ExecutionLog) ProtoReflect() protoreflect.Message {
	mi := &file_types_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionLog.ProtoReflect.Descriptor instead.
func (*ExecutionLog) Descriptor() ([]byte, []int) {
	return file_types_execution_proto_rawDescGZIP(), []int{5}
}

func (x *ExecutionLog) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ExecutionLog) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecutionLog) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

func (x *ExecutionLog) GetTopics() [][]byte {
	if x != nil {
		return x.Topics
	}
	return nil
}

type ExecutionInternalTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	From          []byte                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            []byte                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionInternalTransaction) Reset() {
	*x = ExecutionInternalTransaction{}
	mi := &file_types_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionInternalTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionInternalTransaction) ProtoMessage() {}

func (x *ExecutionInternalTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_types_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionInternalTransaction.ProtoReflect.Descriptor instead.
func (*ExecutionInternalTransaction) Descriptor() ([]byte, []int) {
	return file_types_execution_proto_rawDescGZIP(), []int{6}
}

func (x *ExecutionInternalTransaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExecutionInternalTransaction) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ExecutionInternalTransaction) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ExecutionInternalTransaction) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ExecutionInternalTransaction) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ExecutionInternalTransaction) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ExecutionBlockIndexed struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hash             []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentHash       []byte                 `protobuf:"bytes,2,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Coinbase         []byte                 `protobuf:"bytes,4,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	Number           uint64                 `protobuf:"varint,9,opt,name=number,proto3" json:"number,omitempty"`
	GasLimit         uint64                 `protobuf:"varint,10,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed          uint64                 `protobuf:"varint,11,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Time             *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=time,proto3" json:"time,omitempty"`
	BaseFee          []byte                 `protobuf:"bytes,18,opt,name=base_fee,json=baseFee,proto3" json:"base_fee,omitempty"`
	TransactionCount uint64                 `protobuf:"varint,20,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	LowestGasPrice   []byte                 `protobuf:"bytes,22,opt,name=lowest_gas_price,json=lowestGasPrice,proto3" json:"lowest_gas_price,omitempty"`
	HighestGasPrice  []byte                 `protobuf:"bytes,23,opt,name=highest_gas_price,json=highestGasPrice,proto3" json:"highest_gas_price,omitempty"`
	// uint64 duration = 24;
	TxReward []byte `protobuf:"bytes,25,opt,name=tx_reward,json=txReward,proto3" json:"tx_reward,omitempty"`
	// bytes base_fee_change = 27;
	// bytes block_utilization_change = 28;
	InternalTransactionCount uint64 `protobuf:"varint,29,opt,name=internal_transaction_count,json=internalTransactionCount,proto3" json:"internal_transaction_count,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ExecutionBlockIndexed) Reset() {
	*x = ExecutionBlockIndexed{}
	mi := &file_types_execution_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionBlockIndexed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionBlockIndexed) ProtoMessage() {}

func (x *ExecutionBlockIndexed) ProtoReflect() protoreflect.Message {
	mi := &file_types_execution_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionBlockIndexed.ProtoReflect.Descriptor instead.
func (*ExecutionBlockIndexed) Descriptor() ([]byte, []int) {
	return file_types_execution_proto_rawDescGZIP(), []int{7}
}

func (x *ExecutionBlockIndexed) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ExecutionBlockIndexed) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *ExecutionBlockIndexed) GetCoinbase() []byte {
	if x != nil {
		return x.Coinbase
	}
	return nil
}

func (x *ExecutionBlockIndexed) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *ExecutionBlockIndexed) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *ExecutionBlockIndexed) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *ExecutionBlockIndexed) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ExecutionBlockIndexed) GetBaseFee() []byte {
	if x != nil {
		return x.BaseFee
	}
	return nil
}

func (x *ExecutionBlockIndexed) GetTransactionCount() uint64 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

func (x *ExecutionBlockIndexed) GetLowestGasPrice() []byte {
	if x != nil {
		return x.LowestGasPrice
	}
	return nil
}

func (x *ExecutionBlockIndexed) GetHighestGasPrice() []byte {
	if x != nil {
		return x.HighestGasPrice
	}
	return nil
}

func (x *ExecutionBlockIndexed) GetTxReward() []byte {
	if x != nil {
		return x.TxReward
	}
	return nil
}

func (x *ExecutionBlockIndexed) GetInternalTransactionCount() uint64 {
	if x != nil {
		return x.InternalTransactionCount
	}
	return 0
}

type ExecutionWithdrawalIndexed struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber    uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Index          uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	ValidatorIndex uint64                 `protobuf:"varint,3,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty"`
	Address        []byte                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Amount         []byte                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Time           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutionWithdrawalIndexed) Reset() {
	*x = ExecutionWithdrawalIndexed{}
	mi := &file_types_execution_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionWithdrawalIndexed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionWithdrawalIndexed) ProtoMessage() {}

func (x *ExecutionWithdrawalIndexed) ProtoReflect() protoreflect.Message {
	mi := &file_types_execution_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionWithdrawalIndexed.ProtoReflect.Descriptor instead.
func (*ExecutionWithdrawalIndexed) Descriptor() ([]byte, []int) {
	return file_types_execution_proto_rawDescGZIP(), []int{8}
}

func (x *ExecutionWithdrawalIndexed) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ExecutionWithdrawalIndexed) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ExecutionWithdrawalIndexed) GetValidatorIndex() uint64 {
	if x != nil {
		return x.ValidatorIndex
	}
	return 0
}

func (x *ExecutionWithdrawalIndexed) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ExecutionWithdrawalIndexed) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *ExecutionWithdrawalIndexed) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type ExecutionTransactionIndexed struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Hash               []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	BlockNumber        uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Time               *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	MethodId           []byte                 `protobuf:"bytes,4,opt,name=method_id,json=methodId,proto3" json:"method_id,omitempty"`
	From               []byte                 `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To                 []byte                 `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	Value              []byte                 `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	TxFee              []byte                 `protobuf:"bytes,8,opt,name=tx_fee,json=txFee,proto3" json:"tx_fee,omitempty"`
	GasPrice           []byte                 `protobuf:"bytes,9,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	IsContractCreation bool                   `protobuf:"varint,10,opt,name=is_contract_creation,json=isContractCreation,proto3" json:"is_contract_creation,omitempty"`
	// invokes_contract is unused, should mark reserved!
	InvokesContract bool   `protobuf:"varint,11,opt,name=invokes_contract,json=invokesContract,proto3" json:"invokes_contract,omitempty"`
	ErrorMsg        string `protobuf:"bytes,12,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutionTransactionIndexed) Reset() {
	*x = ExecutionTransactionIndexed{}
	mi := &file_types_execution_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionTransactionIndexed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionTransactionIndexed) ProtoMessage() {}

func (x *ExecutionTransactionIndexed) ProtoReflect() protoreflect.Message {
	mi := &file_types_execution_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionTransactionIndexed.ProtoReflect.Descriptor instead.
func (*ExecutionTransactionIndexed) Descriptor() ([]byte, []int) {
	return file_types_execution_proto_rawDescGZIP(), []int{9}
}

func (x *ExecutionTransactionIndexed) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ExecutionTransactionIndexed) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ExecutionTransactionIndexed) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ExecutionTransactionIndexed) GetMethodId() []byte {
	if x != nil {
		return x.MethodId
	}
	return nil
}

func (x *ExecutionTransactionIndexed) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ExecutionTransactionIndexed) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ExecutionTransactionIndexed) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ExecutionTransactionIndexed) GetTxFee() []byte {
	if x != nil {
		return x.TxFee
	}
	return nil
}

func (x *ExecutionTransactionIndexed) GetGasPrice() []byte {
	if x != nil {
		return x.GasPrice
	}
	return nil
}

func (x *ExecutionTransactionIndexed) GetIsContractCreation() bool {
	if x != nil {
		return x.IsContractCreation
	}
	return false
}

func (x *ExecutionTransactionIndexed) GetInvokesContract() bool {
	if x != nil {
		return x.InvokesContract
	}
	return false
}

func (x *ExecutionTransactionIndexed) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ExecutionInternalTransactionIndexed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentHash    []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	From          []byte                 `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To            []byte                 `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	Value         []byte                 `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionInternalTransactionIndexed) Reset() {
	*x = ExecutionInternalTransactionIndexed{}
	mi := &file_types_execution_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionInternalTransactionIndexed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionInternalTransactionIndexed) ProtoMessage() {}

func (x *ExecutionInternalTransactionIndexed) ProtoReflect() protoreflect.Message {
	mi := &file_types_execution_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionInternalTransactionIndexed.ProtoReflect.Descriptor instead.
func (*ExecutionInternalTransactionIndexed) Descriptor() ([]byte, []int) {
	return file_types_execution_proto_rawDescGZIP(), []int{10}
}

func (x *ExecutionInternalTransactionIndexed) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *ExecutionInternalTransactionIndexed) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ExecutionInternalTransactionIndexed) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExecutionInternalTransactionIndexed) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ExecutionInternalTransactionIndexed) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ExecutionInternalTransactionIndexed) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ExecutionInternalTransactionIndexed) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ExecutionSQRCTF1Indexed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentHash    []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TokenAddress  []byte                 `protobuf:"bytes,3,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	From          []byte                 `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To            []byte                 `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	Value         []byte                 `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionSQRCTF1Indexed) Reset() {
	*x = ExecutionSQRCTF1Indexed{}
	mi := &file_types_execution_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionSQRCTF1Indexed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionSQRCTF1Indexed) ProtoMessage() {}

func (x *ExecutionSQRCTF1Indexed) ProtoReflect() protoreflect.Message {
	mi := &file_types_execution_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionSQRCTF1Indexed.ProtoReflect.Descriptor instead.
func (*ExecutionSQRCTF1Indexed) Descriptor() ([]byte, []int) {
	return file_types_execution_proto_rawDescGZIP(), []int{11}
}

func (x *ExecutionSQRCTF1Indexed) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *ExecutionSQRCTF1Indexed) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ExecutionSQRCTF1Indexed) GetTokenAddress() []byte {
	if x != nil {
		return x.TokenAddress
	}
	return nil
}

func (x *ExecutionSQRCTF1Indexed) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ExecutionSQRCTF1Indexed) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ExecutionSQRCTF1Indexed) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ExecutionSQRCTF1Indexed) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ExecutionSQRCTN1Indexed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentHash    []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TokenAddress  []byte                 `protobuf:"bytes,3,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	From          []byte                 `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To            []byte                 `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	TokenId       []byte                 `protobuf:"bytes,7,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionSQRCTN1Indexed) Reset() {
	*x = ExecutionSQRCTN1Indexed{}
	mi := &file_types_execution_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionSQRCTN1Indexed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionSQRCTN1Indexed) ProtoMessage() {}

func (x *ExecutionSQRCTN1Indexed) ProtoReflect() protoreflect.Message {
	mi := &file_types_execution_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionSQRCTN1Indexed.ProtoReflect.Descriptor instead.
func (*ExecutionSQRCTN1Indexed) Descriptor() ([]byte, []int) {
	return file_types_execution_proto_rawDescGZIP(), []int{12}
}

func (x *ExecutionSQRCTN1Indexed) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *ExecutionSQRCTN1Indexed) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ExecutionSQRCTN1Indexed) GetTokenAddress() []byte {
	if x != nil {
		return x.TokenAddress
	}
	return nil
}

func (x *ExecutionSQRCTN1Indexed) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ExecutionSQRCTN1Indexed) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ExecutionSQRCTN1Indexed) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ExecutionSQRCTN1Indexed) GetTokenId() []byte {
	if x != nil {
		return x.TokenId
	}
	return nil
}

// https://eips.ethereum.org/EIPS/eip-1155
type ExecutionSQRCTB1Indexed struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ParentHash   []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	BlockNumber  uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TokenAddress []byte                 `protobuf:"bytes,3,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Time         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	From         []byte                 `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To           []byte                 `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	TokenId      []byte                 `protobuf:"bytes,7,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Value        []byte                 `protobuf:"bytes,8,opt,name=value,proto3" json:"value,omitempty"`
	// the address approved to make the transfer
	Operator      []byte `protobuf:"bytes,9,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionSQRCTB1Indexed) Reset() {
	*x = ExecutionSQRCTB1Indexed{}
	mi := &file_types_execution_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionSQRCTB1Indexed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionSQRCTB1Indexed) ProtoMessage() {}

func (x *ExecutionSQRCTB1Indexed) ProtoReflect() protoreflect.Message {
	mi := &file_types_execution_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionSQRCTB1Indexed.ProtoReflect.Descriptor instead.
func (*ExecutionSQRCTB1Indexed) Descriptor() ([]byte, []int) {
	return file_types_execution_proto_rawDescGZIP(), []int{13}
}

func (x *ExecutionSQRCTB1Indexed) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *ExecutionSQRCTB1Indexed) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ExecutionSQRCTB1Indexed) GetTokenAddress() []byte {
	if x != nil {
		return x.TokenAddress
	}
	return nil
}

func (x *ExecutionSQRCTB1Indexed) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ExecutionSQRCTB1Indexed) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ExecutionSQRCTB1Indexed) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ExecutionSQRCTB1Indexed) GetTokenId() []byte {
	if x != nil {
		return x.TokenId
	}
	return nil
}

func (x *ExecutionSQRCTB1Indexed) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ExecutionSQRCTB1Indexed) GetOperator() []byte {
	if x != nil {
		return x.Operator
	}
	return nil
}

var File_types_execution_proto protoreflect.FileDescriptor

const file_types_execution_proto_rawDesc = "" +
	"\n" +
	"\x15types/execution.proto\x12\x05types\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x04\n" +
	"\x0eExecutionBlock\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x1f\n" +
	"\vparent_hash\x18\x02 \x01(\fR\n" +
	"parentHash\x12\x1a\n" +
	"\bcoinbase\x18\x04 \x01(\fR\bcoinbase\x12\x12\n" +
	"\x04root\x18\x05 \x01(\fR\x04root\x12\x17\n" +
	"\atx_hash\x18\x06 \x01(\fR\x06txHash\x12!\n" +
	"\freceipt_hash\x18\a \x01(\fR\vreceiptHash\x12\x16\n" +
	"\x06number\x18\t \x01(\x04R\x06number\x12\x1b\n" +
	"\tgas_limit\x18\n" +
	" \x01(\x04R\bgasLimit\x12\x19\n" +
	"\bgas_used\x18\v \x01(\x04R\agasUsed\x12.\n" +
	"\x04time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05extra\x18\r \x01(\fR\x05extra\x12\x16\n" +
	"\x06random\x18\x0e \x01(\fR\x06random\x12\x14\n" +
	"\x05bloom\x18\x11 \x01(\fR\x05bloom\x12\x19\n" +
	"\bbase_fee\x18\x12 \x01(\fR\abaseFee\x12?\n" +
	"\ftransactions\x18\x15 \x03(\v2\x1b.types.ExecutionTransactionR\ftransactions\x12<\n" +
	"\vwithdrawals\x18\x16 \x03(\v2\x1a.types.ExecutionWithdrawalR\vwithdrawals\"\x86\x01\n" +
	"\x13ExecutionWithdrawal\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12'\n" +
	"\x0fvalidator_index\x18\x02 \x01(\x04R\x0evalidatorIndex\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\fR\aaddress\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\fR\x06amount\"\x8e\x05\n" +
	"\x14ExecutionTransaction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\x126\n" +
	"\x18max_priority_fee_per_gas\x18\x04 \x01(\fR\x14maxPriorityFeePerGas\x12%\n" +
	"\x0fmax_fee_per_gas\x18\x05 \x01(\fR\fmaxFeePerGas\x12\x10\n" +
	"\x03gas\x18\x06 \x01(\x04R\x03gas\x12\x14\n" +
	"\x05value\x18\a \x01(\fR\x05value\x12\x12\n" +
	"\x04data\x18\b \x01(\fR\x04data\x12\x0e\n" +
	"\x02to\x18\f \x01(\fR\x02to\x12\x12\n" +
	"\x04from\x18\r \x01(\fR\x04from\x12\x19\n" +
	"\bchain_id\x18\x0e \x01(\fR\achainId\x122\n" +
	"\vaccess_list\x18\x0f \x03(\v2\x11.types.AccessListR\n" +
	"accessList\x12\x12\n" +
	"\x04hash\x18\x10 \x01(\fR\x04hash\x12)\n" +
	"\x10contract_address\x18\x11 \x01(\fR\x0fcontractAddress\x120\n" +
	"\x14commulative_gas_used\x18\x12 \x01(\x04R\x12commulativeGasUsed\x12\x19\n" +
	"\bgas_used\x18\x13 \x01(\x04R\agasUsed\x12\x1d\n" +
	"\n" +
	"logs_bloom\x18\x14 \x01(\fR\tlogsBloom\x12\x16\n" +
	"\x06status\x18\x15 \x01(\x04R\x06status\x12\x1b\n" +
	"\terror_msg\x18\x16 \x01(\tR\berrorMsg\x12'\n" +
	"\x04logs\x18\x17 \x03(\v2\x13.types.ExecutionLogR\x04logs\x125\n" +
	"\x03itx\x18\x18 \x03(\v2#.types.ExecutionInternalTransactionR\x03itx\"M\n" +
	"\x10IsContractUpdate\x12\x1f\n" +
	"\vis_contract\x18\x01 \x01(\bR\n" +
	"isContract\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"I\n" +
	"\n" +
	"AccessList\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12!\n" +
	"\fstorage_keys\x18\x02 \x03(\fR\vstorageKeys\"n\n" +
	"\fExecutionLog\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x18\n" +
	"\aremoved\x18\x03 \x01(\bR\aremoved\x12\x16\n" +
	"\x06topics\x18\x04 \x03(\fR\x06topics\"\x9d\x01\n" +
	"\x1cExecutionInternalTransaction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04from\x18\x02 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\fR\x02to\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12\x1b\n" +
	"\terror_msg\x18\x05 \x01(\tR\berrorMsg\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\"\xe1\x03\n" +
	"\x15ExecutionBlockIndexed\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x1f\n" +
	"\vparent_hash\x18\x02 \x01(\fR\n" +
	"parentHash\x12\x1a\n" +
	"\bcoinbase\x18\x04 \x01(\fR\bcoinbase\x12\x16\n" +
	"\x06number\x18\t \x01(\x04R\x06number\x12\x1b\n" +
	"\tgas_limit\x18\n" +
	" \x01(\x04R\bgasLimit\x12\x19\n" +
	"\bgas_used\x18\v \x01(\x04R\agasUsed\x12.\n" +
	"\x04time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x19\n" +
	"\bbase_fee\x18\x12 \x01(\fR\abaseFee\x12+\n" +
	"\x11transaction_count\x18\x14 \x01(\x04R\x10transactionCount\x12(\n" +
	"\x10lowest_gas_price\x18\x16 \x01(\fR\x0elowestGasPrice\x12*\n" +
	"\x11highest_gas_price\x18\x17 \x01(\fR\x0fhighestGasPrice\x12\x1b\n" +
	"\ttx_reward\x18\x19 \x01(\fR\btxReward\x12<\n" +
	"\x1ainternal_transaction_count\x18\x1d \x01(\x04R\x18internalTransactionCount\"\xe0\x01\n" +
	"\x1aExecutionWithdrawalIndexed\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12'\n" +
	"\x0fvalidator_index\x18\x03 \x01(\x04R\x0evalidatorIndex\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\fR\aaddress\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\fR\x06amount\x12.\n" +
	"\x04time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"\x89\x03\n" +
	"\x1bExecutionTransactionIndexed\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x1b\n" +
	"\tmethod_id\x18\x04 \x01(\fR\bmethodId\x12\x12\n" +
	"\x04from\x18\x05 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x06 \x01(\fR\x02to\x12\x14\n" +
	"\x05value\x18\a \x01(\fR\x05value\x12\x15\n" +
	"\x06tx_fee\x18\b \x01(\fR\x05txFee\x12\x1b\n" +
	"\tgas_price\x18\t \x01(\fR\bgasPrice\x120\n" +
	"\x14is_contract_creation\x18\n" +
	" \x01(\bR\x12isContractCreation\x12)\n" +
	"\x10invokes_contract\x18\v \x01(\bR\x0finvokesContract\x12\x1b\n" +
	"\terror_msg\x18\f \x01(\tR\berrorMsg\"\xe7\x01\n" +
	"#ExecutionInternalTransactionIndexed\x12\x1f\n" +
	"\vparent_hash\x18\x01 \x01(\fR\n" +
	"parentHash\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x12\n" +
	"\x04from\x18\x05 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x06 \x01(\fR\x02to\x12\x14\n" +
	"\x05value\x18\a \x01(\fR\x05value\"\xec\x01\n" +
	"\x17ExecutionSQRCTF1Indexed\x12\x1f\n" +
	"\vparent_hash\x18\x01 \x01(\fR\n" +
	"parentHash\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12#\n" +
	"\rtoken_address\x18\x03 \x01(\fR\ftokenAddress\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x12\n" +
	"\x04from\x18\x05 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x06 \x01(\fR\x02to\x12\x14\n" +
	"\x05value\x18\a \x01(\fR\x05value\"\xf1\x01\n" +
	"\x17ExecutionSQRCTN1Indexed\x12\x1f\n" +
	"\vparent_hash\x18\x01 \x01(\fR\n" +
	"parentHash\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12#\n" +
	"\rtoken_address\x18\x03 \x01(\fR\ftokenAddress\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x12\n" +
	"\x04from\x18\x05 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x06 \x01(\fR\x02to\x12\x19\n" +
	"\btoken_id\x18\a \x01(\fR\atokenId\"\xa3\x02\n" +
	"\x17ExecutionSQRCTB1Indexed\x12\x1f\n" +
	"\vparent_hash\x18\x01 \x01(\fR\n" +
	"parentHash\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12#\n" +
	"\rtoken_address\x18\x03 \x01(\fR\ftokenAddress\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x12\n" +
	"\x04from\x18\x05 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x06 \x01(\fR\x02to\x12\x19\n" +
	"\btoken_id\x18\a \x01(\fR\atokenId\x12\x14\n" +
	"\x05value\x18\b \x01(\fR\x05value\x12\x1a\n" +
	"\boperator\x18\t \x01(\fR\boperatorB\tZ\a./typesb\x06proto3"

var (
	file_types_execution_proto_rawDescOnce sync.Once
	file_types_execution_proto_rawDescData []byte
)

func file_types_execution_proto_rawDescGZIP() []byte {
	file_types_execution_proto_rawDescOnce.Do(func() {
		file_types_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_execution_proto_rawDesc), len(file_types_execution_proto_rawDesc)))
	})
	return file_types_execution_proto_rawDescData
}

var file_types_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_types_execution_proto_goTypes = []any{
	(*ExecutionBlock)(nil),                      // 0: types.ExecutionBlock
	(*ExecutionWithdrawal)(nil),                 // 1: types.ExecutionWithdrawal
	(*ExecutionTransaction)(nil),                // 2: types.ExecutionTransaction
	(*IsContractUpdate)(nil),                    // 3: types.IsContractUpdate
	(*AccessList)(nil),                          // 4: types.AccessList
	(*ExecutionLog)(nil),                        // 5: types.ExecutionLog
	(*ExecutionInternalTransaction)(nil),        // 6: types.ExecutionInternalTransaction
	(*ExecutionBlockIndexed)(nil),               // 7: types.ExecutionBlockIndexed
	(*ExecutionWithdrawalIndexed)(nil),          // 8: types.ExecutionWithdrawalIndexed
	(*ExecutionTransactionIndexed)(nil),         // 9: types.ExecutionTransactionIndexed
	(*ExecutionInternalTransactionIndexed)(nil), // 10: types.ExecutionInternalTransactionIndexed
	(*ExecutionSQRCTF1Indexed)(nil),             // 11: types.ExecutionSQRCTF1Indexed
	(*ExecutionSQRCTN1Indexed)(nil),             // 12: types.ExecutionSQRCTN1Indexed
	(*ExecutionSQRCTB1Indexed)(nil),             // 13: types.ExecutionSQRCTB1Indexed
	(*timestamppb.Timestamp)(nil),               // 14: google.protobuf.Timestamp
}
var file_types_execution_proto_depIdxs = []int32{
	14, // 0: types.ExecutionBlock.time:type_name -> google.protobuf.Timestamp
	2,  // 1: types.ExecutionBlock.transactions:type_name -> types.ExecutionTransaction
	1,  // 2: types.ExecutionBlock.withdrawals:type_name -> types.ExecutionWithdrawal
	4,  // 3: types.ExecutionTransaction.access_list:type_name -> types.AccessList
	5,  // 4: types.ExecutionTransaction.logs:type_name -> types.ExecutionLog
	6,  // 5: types.ExecutionTransaction.itx:type_name -> types.ExecutionInternalTransaction
	14, // 6: types.ExecutionBlockIndexed.time:type_name -> google.protobuf.Timestamp
	14, // 7: types.ExecutionWithdrawalIndexed.time:type_name -> google.protobuf.Timestamp
	14, // 8: types.ExecutionTransactionIndexed.time:type_name -> google.protobuf.Timestamp
	14, // 9: types.ExecutionInternalTransactionIndexed.time:type_name -> google.protobuf.Timestamp
	14, // 10: types.ExecutionSQRCTF1Indexed.time:type_name -> google.protobuf.Timestamp
	14, // 11: types.ExecutionSQRCTN1Indexed.time:type_name -> google.protobuf.Timestamp
	14, // 12: types.ExecutionSQRCTB1Indexed.time:type_name -> google.protobuf.Timestamp
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_types_execution_proto_init() }
func file_types_execution_proto_init() {
	if File_types_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_execution_proto_rawDesc), len(file_types_execution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_execution_proto_goTypes,
		DependencyIndexes: file_types_execution_proto_depIdxs,
		MessageInfos:      file_types_execution_proto_msgTypes,
	}.Build()
	File_types_execution_proto = out.File
	file_types_execution_proto_goTypes = nil
	file_types_execution_proto_depIdxs = nil
}
