// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.0
// source: types/qrns.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QrnsNameRegistered struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ParentHash       []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	BlockNumber      uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	RegisterContract []byte                 `protobuf:"bytes,3,opt,name=register_contract,json=registerContract,proto3" json:"register_contract,omitempty"`
	ResolverContract []byte                 `protobuf:"bytes,4,opt,name=resolver_contract,json=resolverContract,proto3" json:"resolver_contract,omitempty"`
	Time             *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	Label            []byte                 `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	Owner            []byte                 `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	Resolver         []byte                 `protobuf:"bytes,8,opt,name=resolver,proto3" json:"resolver,omitempty"`
	Node             []byte                 `protobuf:"bytes,9,opt,name=node,proto3" json:"node,omitempty"`
	Name             []byte                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Expires          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QrnsNameRegistered) Reset() {
	*x = QrnsNameRegistered{}
	mi := &file_types_qrns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QrnsNameRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrnsNameRegistered) ProtoMessage() {}

func (x *QrnsNameRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_types_qrns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrnsNameRegistered.ProtoReflect.Descriptor instead.
func (*QrnsNameRegistered) Descriptor() ([]byte, []int) {
	return file_types_qrns_proto_rawDescGZIP(), []int{0}
}

func (x *QrnsNameRegistered) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *QrnsNameRegistered) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *QrnsNameRegistered) GetRegisterContract() []byte {
	if x != nil {
		return x.RegisterContract
	}
	return nil
}

func (x *QrnsNameRegistered) GetResolverContract() []byte {
	if x != nil {
		return x.ResolverContract
	}
	return nil
}

func (x *QrnsNameRegistered) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *QrnsNameRegistered) GetLabel() []byte {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *QrnsNameRegistered) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *QrnsNameRegistered) GetResolver() []byte {
	if x != nil {
		return x.Resolver
	}
	return nil
}

func (x *QrnsNameRegistered) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *QrnsNameRegistered) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *QrnsNameRegistered) GetExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.Expires
	}
	return nil
}

type QrnsNameRenewed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentHash    []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Label         []byte                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Name          []byte                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Expires       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QrnsNameRenewed) Reset() {
	*x = QrnsNameRenewed{}
	mi := &file_types_qrns_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QrnsNameRenewed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrnsNameRenewed) ProtoMessage() {}

func (x *QrnsNameRenewed) ProtoReflect() protoreflect.Message {
	mi := &file_types_qrns_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrnsNameRenewed.ProtoReflect.Descriptor instead.
func (*QrnsNameRenewed) Descriptor() ([]byte, []int) {
	return file_types_qrns_proto_rawDescGZIP(), []int{1}
}

func (x *QrnsNameRenewed) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *QrnsNameRenewed) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *QrnsNameRenewed) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *QrnsNameRenewed) GetLabel() []byte {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *QrnsNameRenewed) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *QrnsNameRenewed) GetExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.Expires
	}
	return nil
}

type QrnsAddressChanged struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParentHash      []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	BlockNumber     uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	ResolveContract []byte                 `protobuf:"bytes,3,opt,name=resolve_contract,json=resolveContract,proto3" json:"resolve_contract,omitempty"`
	Time            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Node            []byte                 `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	CoinType        uint64                 `protobuf:"varint,6,opt,name=coin_type,json=coinType,proto3" json:"coin_type,omitempty"`
	NewAddress      []byte                 `protobuf:"bytes,7,opt,name=new_address,json=newAddress,proto3" json:"new_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QrnsAddressChanged) Reset() {
	*x = QrnsAddressChanged{}
	mi := &file_types_qrns_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QrnsAddressChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrnsAddressChanged) ProtoMessage() {}

func (x *QrnsAddressChanged) ProtoReflect() protoreflect.Message {
	mi := &file_types_qrns_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrnsAddressChanged.ProtoReflect.Descriptor instead.
func (*QrnsAddressChanged) Descriptor() ([]byte, []int) {
	return file_types_qrns_proto_rawDescGZIP(), []int{2}
}

func (x *QrnsAddressChanged) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *QrnsAddressChanged) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *QrnsAddressChanged) GetResolveContract() []byte {
	if x != nil {
		return x.ResolveContract
	}
	return nil
}

func (x *QrnsAddressChanged) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *QrnsAddressChanged) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *QrnsAddressChanged) GetCoinType() uint64 {
	if x != nil {
		return x.CoinType
	}
	return 0
}

func (x *QrnsAddressChanged) GetNewAddress() []byte {
	if x != nil {
		return x.NewAddress
	}
	return nil
}

type QrnsNameChanged struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParentHash      []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	BlockNumber     uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	ResolveContract []byte                 `protobuf:"bytes,3,opt,name=resolve_contract,json=resolveContract,proto3" json:"resolve_contract,omitempty"`
	Time            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Node            []byte                 `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	NewName         []byte                 `protobuf:"bytes,6,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QrnsNameChanged) Reset() {
	*x = QrnsNameChanged{}
	mi := &file_types_qrns_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QrnsNameChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrnsNameChanged) ProtoMessage() {}

func (x *QrnsNameChanged) ProtoReflect() protoreflect.Message {
	mi := &file_types_qrns_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrnsNameChanged.ProtoReflect.Descriptor instead.
func (*QrnsNameChanged) Descriptor() ([]byte, []int) {
	return file_types_qrns_proto_rawDescGZIP(), []int{3}
}

func (x *QrnsNameChanged) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *QrnsNameChanged) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *QrnsNameChanged) GetResolveContract() []byte {
	if x != nil {
		return x.ResolveContract
	}
	return nil
}

func (x *QrnsNameChanged) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *QrnsNameChanged) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *QrnsNameChanged) GetNewName() []byte {
	if x != nil {
		return x.NewName
	}
	return nil
}

var File_types_qrns_proto protoreflect.FileDescriptor

const file_types_qrns_proto_rawDesc = "" +
	"\n" +
	"\x10types/qrns.proto\x12\x05types\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x03\n" +
	"\x12QrnsNameRegistered\x12\x1f\n" +
	"\vparent_hash\x18\x01 \x01(\fR\n" +
	"parentHash\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12+\n" +
	"\x11register_contract\x18\x03 \x01(\fR\x10registerContract\x12+\n" +
	"\x11resolver_contract\x18\x04 \x01(\fR\x10resolverContract\x12.\n" +
	"\x04time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05label\x18\x06 \x01(\fR\x05label\x12\x14\n" +
	"\x05owner\x18\a \x01(\fR\x05owner\x12\x1a\n" +
	"\bresolver\x18\b \x01(\fR\bresolver\x12\x12\n" +
	"\x04node\x18\t \x01(\fR\x04node\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\fR\x04name\x124\n" +
	"\aexpires\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\aexpires\"\xe5\x01\n" +
	"\x0fQrnsNameRenewed\x12\x1f\n" +
	"\vparent_hash\x18\x01 \x01(\fR\n" +
	"parentHash\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05label\x18\x04 \x01(\fR\x05label\x12\x12\n" +
	"\x04name\x18\x05 \x01(\fR\x04name\x124\n" +
	"\aexpires\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aexpires\"\x85\x02\n" +
	"\x12QrnsAddressChanged\x12\x1f\n" +
	"\vparent_hash\x18\x01 \x01(\fR\n" +
	"parentHash\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12)\n" +
	"\x10resolve_contract\x18\x03 \x01(\fR\x0fresolveContract\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x12\n" +
	"\x04node\x18\x05 \x01(\fR\x04node\x12\x1b\n" +
	"\tcoin_type\x18\x06 \x01(\x04R\bcoinType\x12\x1f\n" +
	"\vnew_address\x18\a \x01(\fR\n" +
	"newAddress\"\xdf\x01\n" +
	"\x0fQrnsNameChanged\x12\x1f\n" +
	"\vparent_hash\x18\x01 \x01(\fR\n" +
	"parentHash\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12)\n" +
	"\x10resolve_contract\x18\x03 \x01(\fR\x0fresolveContract\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x12\n" +
	"\x04node\x18\x05 \x01(\fR\x04node\x12\x19\n" +
	"\bnew_name\x18\x06 \x01(\fR\anewNameB\tZ\a./typesb\x06proto3"

var (
	file_types_qrns_proto_rawDescOnce sync.Once
	file_types_qrns_proto_rawDescData []byte
)

func file_types_qrns_proto_rawDescGZIP() []byte {
	file_types_qrns_proto_rawDescOnce.Do(func() {
		file_types_qrns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_qrns_proto_rawDesc), len(file_types_qrns_proto_rawDesc)))
	})
	return file_types_qrns_proto_rawDescData
}

var file_types_qrns_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_types_qrns_proto_goTypes = []any{
	(*QrnsNameRegistered)(nil),    // 0: types.QrnsNameRegistered
	(*QrnsNameRenewed)(nil),       // 1: types.QrnsNameRenewed
	(*QrnsAddressChanged)(nil),    // 2: types.QrnsAddressChanged
	(*QrnsNameChanged)(nil),       // 3: types.QrnsNameChanged
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_types_qrns_proto_depIdxs = []int32{
	4, // 0: types.QrnsNameRegistered.time:type_name -> google.protobuf.Timestamp
	4, // 1: types.QrnsNameRegistered.expires:type_name -> google.protobuf.Timestamp
	4, // 2: types.QrnsNameRenewed.time:type_name -> google.protobuf.Timestamp
	4, // 3: types.QrnsNameRenewed.expires:type_name -> google.protobuf.Timestamp
	4, // 4: types.QrnsAddressChanged.time:type_name -> google.protobuf.Timestamp
	4, // 5: types.QrnsNameChanged.time:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_types_qrns_proto_init() }
func file_types_qrns_proto_init() {
	if File_types_qrns_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_qrns_proto_rawDesc), len(file_types_qrns_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_qrns_proto_goTypes,
		DependencyIndexes: file_types_qrns_proto_depIdxs,
		MessageInfos:      file_types_qrns_proto_msgTypes,
	}.Build()
	File_types_qrns_proto = out.File
	file_types_qrns_proto_goTypes = nil
	file_types_qrns_proto_depIdxs = nil
}
