version: '3'
x-service: &default-service
  image: golang:1.24
  working_dir: /app
  volumes:
    - ../.:/app
    - /tmp/go-cache:/go
    - /tmp/go-build-cache:/root/.cache/go-build
services:
  # TODO(now.youtrack.cloud/issue/TZB-2)
  build-once:
    <<: *default-service
    profiles:
      - build-once
    command: /bin/bash -c "trap stopit SIGINT; stopit() { echo 'trapped SIGINT'; exit; }; git config --global --add safe.directory '*' && make -B all"
  indexer:
    <<: *default-service
    command: go run ./cmd/explorer -config /app/local-deployment/config.yml
    environment:
      - INDEXER_ENABLED=true
  el-indexer:
    <<: *default-service
    command: go run ./cmd/el-indexer -config /app/local-deployment/config.yml -blocks.concurrency 1 -data.concurrency 1 --balances.enabled
    # TODO(now.youtrack.cloud/issue/TZB-7)
    # command: go run ./cmd/el-indexer -config /app/local-deployment/config.yml -blocks.concurrency 1 -blocks.tracemode 'gzond' -data.concurrency 1 --balances.enabled
  
  rewards-exporter:
    <<: *default-service
    command: go run ./cmd/rewards-exporter -config /app/local-deployment/config.yml
  statistics:
    <<: *default-service
    command: go run ./cmd/statistics -config /app/local-deployment/config.yml --charts.enabled --graffiti.enabled -validators.enabled
  frontend-data-updater:
    <<: *default-service
    command: go run ./cmd/frontend-data-updater -config /app/local-deployment/config.yml
  frontend:
    <<: *default-service
    command: go run ./cmd/explorer -config /app/local-deployment/config.yml
    ports:
      - "8080:8080"
  
  misc:
    <<: *default-service
    command: /bin/bash -c "trap stopit SIGINT; stopit() { echo 'trapped SIGINT'; exit; }; while true; do date; sleep 1; done"
  redis-sessions:
    image: redis:7
    volumes:
      - redis-sessions:/data
    ports:
      - "$REDIS_SESSIONS_PORT:6379"

volumes:
  redis-sessions:
