name: Static Check

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - staging
      - main

jobs:
  ci:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        go: ["1.24.x"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: WillAbides/setup-go-faster@v1.14.0
      with:
        go-version: ${{ matrix.go }}
    - run: make all				
    - run: "go test ./..."
    - run: "go vet ./..."
    - uses: dominikh/staticcheck-action@v1.3.1
      with:
        version: "2025.1.1" # see https://github.com/dominikh/go-tools/releases
        install-go: false
        cache-key: ${{ matrix.go }}